apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: iuq1vzpnu-python 
  janus-idp.io/tekton: iuq1vzpnu-python
  backstage.io/kubernetes-id: iuq1vzpnu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iuq1vzpnu-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  