apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iuq1vzpnu-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iuq1vzpnu-python 
  name: iuq1vzpnu-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: iuq1vzpnu-python 
